# Generated by Django 4.0.4 on 2022-04-24 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name_plural': 'Brokers'},
        ),
    ]
